#!/usr/bin/env bash

# Load utility methods
. "\$ROOT_DIR/utils"

checkusage "$0" "$#"

key="$1"
default_value="${2:-}"

value=$(jq -r "$key" "$HOME/.$(cat "$ROOT_DIR"/app/.name)rc.json" | sed 's/^null$//')

if [ "$value" != "" ]
then
    echo "$value"
elif [ -n "$default_value" ]
then
    echo "$default_value"
else
    exit 1
fi
